export PROJECT_NAME="yourproject"
export PKG_NAME="yourpackage"
export GITHUB_ORGANIZATION_NAME="YourOrg"
export YOUR_NAME="yourself"
export PACKAGE_DEVELOPER="yourself-yourorg"
export YOUR_EMAIL="yourself.yourorg@gmail.com"
