/*
 * DO NOT EDIT - This file is generated by
 * execution of concatenateTheSlides.sh
 */
var sections = {
    A: "Tutorial01_PrepareTheMachine"
  , B: "Tutorial02_VersionControlInTheCloud"
  , C: "Tutorial03_UnitTestAModule"
  , D: "Tutorial04_CodingStyleAndLinting"
  , E: "Tutorial05_AutomaticDocumentationInTheCloud"
  , F: "Tutorial06_CloudContinuousIntegration"
  , G: "Tutorial07_ProductionLogging"
  , H: "Tutorial08_RealWorldPackage"
  , I: "Tutorial09_PackageSelfTest"
  , J: "Tutorial10_AutomatedDeployment"
};
